---
- name: install php and libs
  dnf: name={{ item }} state=installed
  with_items:
    - php-xml
    - php
    - php-zip
    - php-mbstring
    - php-mysqlnd
    - php-gd
  notify:
  - restart apache
